### PR TITLE
CI: override min peers

### PR DESCRIPTION
**Pull request by TomVasile**
changes:
- sets `min_peers_for_initialization = 0` in config.toml. 

notes:
- the node was starting but continually spewing `Initialize: awaiting sufficient fully-connected peers`

### CODE REVIEW

**Review by hoffmannjan — APPROVED** [review]

**Comment by RitaMAllenCA** [comment]
@TomVasile @hoffmannjan Is there an issue created that I can connect this to?  I am adding the PR to the current sprint for visibility only, since it appears it will merge soon. 

Next question: Jan - will this be in the NEXT release of the SDK or did it go out already? I tagged it for the next release but let me know if that should change.

**Comment by hoffmannjan** [comment]
@RitaMAllenCA it's more of the CI / testing issue so it won't be part of any release, more internal/relability stuff :)

**Comment by hoffmannjan** [comment]
Screenshot 2023-01-30 at 15 25 11
I checked over nctl & casper-node v`1.4.13` - it works. 

Now trying over `dev` branch in `casper-node`

**Comment by hoffmannjan** [comment]
I reverted my test changes and force pushed to this branch. After [this PR will be merged](https://github.com/casper-network/casper-node/pull/3635) we should be good :)

**Comment by hoffmannjan** [comment]
In fact we can already merge this, and tests will stop failing after the previously mentioned PR in L1 will be merged.

**Pull request merged**
