### PR TITLE
feat: Extend SSE client with options, include headers

### PR DESCRIPTION
**Pull request by Volodymyr-Kuchinskyi**
The purpose of this PR is to extend current SSE client configuration to support custom http headers.

### CODE REVIEW

**Comment by gyroflaw** [comment]
@Volodymyr-Kuchinskyi , could you please rebase your branch against the latest dev branch? thank you

**Review by hoffmannjan — APPROVED** [review]
Works good for me!

**Comment by hoffmannjan** [comment]
These will go to `2.16.0`, should be public next week.

**Comment by alexmyshchyshyn** [comment]
Already been implemented as part of version `5.0.0`. Therefore, I am closing this pull request to avoid duplication.

**Pull request closed without merging**
